apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod 
  namespace: my-namespace
spec:
  restartPolicy: Never
  containers:
    - name: sleep-container
      image: busybox
      command: ["sh", "-c", "echo hello world && sleep 300"]